# Generated by Django 5.1.5 on 2025-01-30 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('area', models.CharField(choices=[('C', 'Consulting'), ('II', 'Internal Initiative'), ('OTH', 'Other')], max_length=3)),
                ('status', models.CharField(choices=[('A', 'Active'), ('OH', 'On hold'), ('C', 'Completed')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_lead_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('tech_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_lead_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
