# Generated by Django 5.1.5 on 2025-01-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_area_timeentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='user_id',
            new_name='user',
        ),
    ]
