# Generated by Django 5.1.5 on 2025-02-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_id_timeentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on-hold', 'On hold'), ('completed', 'Completed')], default='active', max_length=10, null=True),
        ),
    ]
