# Generated by Django 5.1.5 on 2025-02-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.CharField(choices=[('C', 'Consulting'), ('RI', 'Research Initiative'), ('II', 'Internal Initiative'), ('OTH', 'Other'), ('CA', 'Client Acquisition')], default='OTH', max_length=3, null=True),
        ),
    ]
