# Generated by Django 5.1.5 on 2025-03-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on-hold', 'On hold'), ('completed', 'Completed'), ('prospect', 'Prospect')], default='active', max_length=10, null=True),
        ),
    ]
