# Generated by Django 5.1.5 on 2025-01-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('area', models.CharField(choices=[('C', 'Consulting'), ('I', 'Internal Initiative'), ('P', 'Product Development')], max_length=2)),
                ('status', models.CharField(choices=[('A', 'Active'), ('OH', 'On hold'), ('C', 'Completed')], default='A', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
