version: '3.8'

services:
  
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - dev.env
    networks:
      - backend

  # Nginx Frontend
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
    volumes:
      - ./frontend:/usr/share/nginx/html  # Serve frontend files
    ports:
      - "80:80"  # Expose Nginx on port 80
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  static_volume:
