version: '3.8'

services:
  # Django Backend (API)
  db:
    image: postgres:17
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    networks:
      - backend
  

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
    networks:
      - backend

  # Nginx Frontend
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
    volumes:
      - ./frontend:/usr/share/nginx/html  # Serve frontend files
    ports:
      - "80:80"  # Expose Nginx on port 80
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_dev_data:
  static_volume:
