version: '3.8'

services:
  # Django Backend (API)
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend

  web:
    build: ./backend
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

  # Nginx Frontend
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
    volumes:
      - ./frontend:/usr/share/nginx/html  # Serve frontend files
    ports:
      - "80:80"  # Expose Nginx on port 80
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
