version: '3.8'

services:
  # Django Backend (API)
  timetracking:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/home/app/web/staticfiles
    networks:
      - backend

  # Nginx Frontend
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend:/usr/share/nginx/html  # Serve frontend files
      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"  # Expose Nginx on port 80
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  static_volume:
